# Generated by Django 2.2.7 on 2019-12-31 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('params', models.TextField(verbose_name='{"max":1201, "min":21123}')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('data_name', models.TextField(primary_key=True, serialize=False)),
                ('is_personal', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=True)),
                ('engine', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RequestApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkey', models.TextField()),
                ('pubkey', models.TextField()),
                ('challenge', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.RequestApplication')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='fields',
            field=models.ManyToManyField(to='rest.ApplicationField'),
        ),
    ]
