# Generated by Django 2.2.7 on 2019-12-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
